|==================================================================================================|
Sub Deletions
|Deletions:

|-------------------------------------------------------
|LARGE GROUP Deletions - Left Variable Indication:
	/if (${Cursor.Name.Left[7].Equal[Bronze ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[6].Equal[Cloth ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[16].Equal[Composite Field ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[20].Equal[Concentrated Grade A]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[29].Equal[Consigned Bite of the Shissar]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[11].Equal[Crude Adept]}) /varset intKeep 0
	/if (${Cursor.Name.Left[15].Equal[Crude Combatant]}) /varset intKeep 0
	/if (${Cursor.Name.Left[14].Equal[Crude Defiant ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[18].Equal[Elaborate Defiant ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[11].Equal[Fine Steel ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[15].Equal[Flawed Defiant ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[9].Equal[Gossamer ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[18].Equal[Intricate Defiant ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[5].Equal[Iron ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[5].Equal[Mesh ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[15].Equal[Ornate Defiant ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[16].Equal[Purified Grade A]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[16].Equal[Purified Grade B]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[9].Equal[Raw-hide ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[15].Equal[Refined Grade A]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[22].Equal[Reinforced Incnediary ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[9].Equal[Ringmail ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[14].Equal[Rough Defiant ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[6].Equal[Rusty ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[12].Equal[Small Cloth ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[11].Equal[Small Iron ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[15].Equal[Small Raw-hide ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[15].Equal[Small Ringmail ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[15].Equal[Simple Defiant ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[14].Equal[Tattered Silk ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[18].Equal[Worn Scattercloud ]}) /varset intKeep 0 
	/if (${Cursor.Name.Left[15].Equal[Woven Crescent ]}) /varset intKeep 0 
|
|-------------------------------------------------------
|LARGE GROUP Deletions - Right Variable Indication:
	/if (${Cursor.Name.Right[9].Equal[ Caladium]}) /varset intKeep 0 
	/if (${Cursor.Name.Right[11].Equal[ Delphinium]}) /varset intKeep 0 
	/if (${Cursor.Name.Right[9].Equal[ Laburnum]}) /varset intKeep 0 
	/if (${Cursor.Name.Right[9].Equal[ Larkspur]}) /varset intKeep 0 
	/if (${Cursor.Name.Right[9].Equal[ Muscimol]}) /varset intKeep 0 
	/if (${Cursor.Name.Right[9].Equal[ Oleander]}) /varset intKeep 0 
|
|-------------------------------------------------------
|Acrylia Caverns Deletions:
	/if (${Cursor.Name.Equal[Breath of Ro]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Filth Covered Battle Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Filth Covered Bone Spear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Filth Covered Dagger]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Filth Covered Great Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Filth Covered Machete]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Filth Covered Stone Spear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 378]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 379]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 400]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 401]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 415]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 416]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 449]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 450]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Part of Toharon's Memoir Pg. 18]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Acrylia Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Ap`Sagor]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Crippling]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Fennin Ro]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Frost]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Gale]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Impetus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Impulse]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Incitement]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Rathe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of the Astral]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wing of Xegony]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Acquisition (Beza)]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Bondage]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Ethereal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Crippling Force]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Grappling]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Odus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Requisition]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of the Ethereal]}) /varset intKeep 0 
|-------------------------------------------------------
|Blackburrow Deletions:
	/if (${Cursor.Name.Equal[Gnoll Teeth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vial of Gnoll Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wrext Mal Insignia]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wrext Mal Sacrificial Blade]}) /varset intKeep 0 
|-------------------------------------------------------
|Blackfeather Roost Deletions:
	/if (${Cursor.Name.Equal[Blackfeather Noble's Gloves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bloom of the Elddar]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bracer of the Roost]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cloak of Lost Essence]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crushed Diamond Dust]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Down Padded Wrist Wrap]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Eletyl's Charm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Feather Down Shirt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Griffon Beak]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Griffon Eggs]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Griffon Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Griffon Feathers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Griffon Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Griffon Pinion Feather]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Harpy Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Harpy Down Feathers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Harpy Feather]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Harpy Pinion Feather]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Large Griffon Pinion Feather]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Large Harpy Pinion Feather]}) /varset intKeep 0 
|-------------------------------------------------------
|Burning Woods Deletions:
	/if (${Cursor.Name.Equal[A Tump Stump]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Axe of the Iron Back]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hammer of Flattening]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lumberjack's Cap]}) /varset intKeep 0 
|-------------------------------------------------------
|Castle Mistmoore / Permafrost Deletions:
	/if (${Cursor.Name.Equal[A Stone Marker]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ashroot]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Black Silk Gloves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Block of Permafrost]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bloodstone Eyepatch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chunk of Amorphous Granite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chunk of Prismatic Metal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cold Iron Morning Star]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Complex Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Complex Etched Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Complex Platinum Etched Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Complex Platinum Silvered Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Complex Velium Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cracked Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crested Mistmoore Shield]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Desiccated Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elementary Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Essence of Moonlight]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Essence of Winter]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Gold Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Platinum Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Platinum Etched Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Platinum Silvered Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Velium Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Familiar Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flame Agate]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Frost Goblin Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Giant Wood Spider Thorax]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Giant Wood Spider Femur]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Glinting Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Goblin Frost Totem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gold Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gold Etched Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gold Painted Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Heart of Frost]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ice Giant Toes]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ice Goblin Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ivory]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Icy Greaves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Large Brick of High Quality Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Large Brick of Unrefined Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Makeshift Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mistmoore Granite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mithril Earring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Natural Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Onyx]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ornate Defiant Chain Gauntlets]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Permafrost Snowball]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Painted Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Silvered Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Polished Crysolite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Prickly Pear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Fine Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Fine Runic Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Runic Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Supple Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Ivy]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rusty Broad Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rusty Long Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sacrificial Dagger]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silverwing Circlet]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silverwing Loop]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silvery Two Handed Axe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silvery War Axe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silvril Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simple Defiant Bow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simple Defiant Chain Tunic]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simple Defiant Plate Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simple Defiant Plate Gauntlets]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simple Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simple Etched Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sir Bronthas's Remains]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Brick of High Quality Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Snowfall Algae]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Splinted Bronze Cloak]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Splintering Club]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Steel Knuckles]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sunshard Dust]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Symbol of Loyalty to Vox]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tacky Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tares Lichen]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Thick Caustic Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Throwing Boulder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Unholy Coldstone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velium Embossed Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velium Silvered Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vial of Vampire Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Weighted Gloves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[White Wolf-hide Cloak]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wolf Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wooly Spider Silk Net]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Dissolution]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Zaharn's Coronet]}) /varset intKeep 0 
|-------------------------------------------------------
|Chardok Deletions:
	|/if (${Cursor.Name.Equal[Singed Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chokidai Hide]}) /varset intKeep 0 
|-------------------------------------------------------
|Cobalt Scar Deletions:
	/if (${Cursor.Name.Equal[Bloodstone Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fatty Walrus Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Golden Earring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimiore Pg. 351]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silver Earring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silver Ring]}) /varset intKeep 0 
|-------------------------------------------------------
|Commonlands Deletions:
	/if (${Cursor.Name.Equal[Chunk of Meat]}) /varset intKeep 0 
	|----------------------------------------------------------**| 
	/if (${Cursor.Name.Equal[Spiderling Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiderling Legs]}) /varset intKeep 0 
	|----------------------------------------------------------**| 
	/if (${Cursor.Name.Equal[Bear Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Black Bear Paw]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grizzly Bear Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ruined Bear Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Thick Grizzly Bear Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Young Kodiak Paw]}) /varset intKeep 0 
	|----------------------------------------------------------**| 
	/if (${Cursor.Name.Equal[Greater Cat Paw]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Greater Cat Tooth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lion Mane]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lion Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lion Tail]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Matted Greater Cat Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mountain Lion Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Puma Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ruined Cat Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ruined Lion Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Young Plains Cat Backbone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Young Plains Cat Scalp]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Young Puma Skin]}) /varset intKeep 0 
	|----------------------------------------------------------**| 
	/if (${Cursor.Name.Equal[Dingy Arm Bands]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Dingy Cap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Gloves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Gorget]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Sash]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Shawl]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Slippers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Trousers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Veil]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dingy Vest]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shadeling Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sharp Bloodling Mandible]}) /varset intKeep 0 
|-------------------------------------------------------
|Crescent Reach Deletions:
	/if (${Cursor.Name.Equal[Grizzly Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Large Stained Bear Tooth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mangled Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Bear Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Rough Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Star Rose Quartz]}) /varset intKeep 0 
|-------------------------------------------------------
|Crypt of Nadox Deletions:
	/if (${Cursor.Name.Equal[Zraxthril Forged Axe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Zraxthril Forged Cutlass]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Zraxthril Forged Flamberge]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Zraxthril Forged Mace]}) /varset intKeep 0 
|-------------------------------------------------------
|Dawnshroud Peaks Deletions:
	/if (${Cursor.Name.Equal[Aged Gold Coin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Aged Platinum Symbol]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Air Marked Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ancestral Statuette]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ancient Petrified Tulip]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ancient Pottery]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ancient Tablet]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bag of Scarlet Sand]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Beaded Circlet]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Black Pearl Studded Emblem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Black Pearl Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blessed Water]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blue Egg]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Book of Inspiration]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Book of Wizardry]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chilled Brazier]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cloud Jewel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Coiled Steel Wire]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Collector's Tribal Belt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crushed Skull]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crystalline Idol]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crystallized Dew]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dark Gem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dark Hued Wood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Diamond Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dread Leech Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Earth Marked Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Emerald Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Enchanted Bundle of Wood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engraved Emerald Statuette]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engraved Fire Opal Statuette]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engraved Ivory Statuette]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engraved Platinum Statuette]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engraved Star Sapphire Statuette]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engraved Wooded Statuette]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Tablet]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Eyeball]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fanged Talisman]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fastened Links]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fiery Gourd]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fiery Sand]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Steel Dagger]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Steel Great Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fire Etched Wand]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fire Blossom]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fire Emerald Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fire Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fire Scorched Stick]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flaming Candle]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fleshy Vine]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fluorescent Gem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Galorian Bone Fragments]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gem of Blue Skies]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Genalan's Chronicles]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gilded Beads]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gilded Branch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gilded Steel Rod]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gleaming Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Glinting Sunstone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Glorious Flower]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Golden Spoon]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Golden Torch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grail of Enchantment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Great Gem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hardened Agate]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hardened Bone Halberd]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hardened Clay Sculpture]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Healing Stone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Heavy Iron Ulak]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hope Ruby]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hope Sapphire]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hope Star Ruby]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hope Quartz]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Jagged Stone Battle Axe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[King's Tome]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Leather Handled Mandible Blade]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Life Gem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lightcrawler Legs]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lightning Dust]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lucid Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Anthems]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Arms]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Augery]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Blessings]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Bravery]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Charm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Composition]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Contention]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Courage]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Creatures]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Cunning]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Dark Fate]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Defiance]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Destiny]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Destruction]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Detonation]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Dread]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Entertainment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Fear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Gloom]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Glory]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Heart]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Honor]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Horror]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Melody]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Music]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Night]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Opposition]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Potential]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Pride]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Reliance]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Righteousness]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Rivers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Rythm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Secrecy]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Song]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Souls]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Spirit]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Stone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Tenor]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Drum]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Mandolin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Martial]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Naturalist]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Noble]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Shark]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Steadfast]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Valor]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Warfare]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Memory Crystal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Meteor Jewel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Opal Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Opaque Glasses]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Oracle's Orb]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Page of Prose]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Painted Ornament]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Peridot Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Petrified Toes]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Polished Chitin Blade]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Polished Chitin Wingblade]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Polished Ivory Idol]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Polished Steel Ulak]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Porous Rock]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Primitive Totem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Red Stone Idol]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rockhopper Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune Stone Brazier]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Runed Ring of Earth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Runic Card]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sack of Shadowed Soil]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sambata Boulder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sambata Warhammer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sapphire Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Scorched Rock]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Seared Brand]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shimmering Lightcrawler Shell]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silverwing Shoulderpads]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sky Jewel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Meteor Fragment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Snake Scale Sceptre]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spirit Marked Ornament]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Star Dust]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Star Sapphire Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sun Stained Steel Rod]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sunflower Fruit]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tablet of Spirits]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Torn Limb]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tro Jeg Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tro Jeg Toes]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[True Silver Idol]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Twilight Fish Scales]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Veiled Lantern]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velvet Sleeves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vial of Aqua Waters]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vial of Firewater]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vial of Purified Earth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Water Idol]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Water Marked Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Weathered Yew Wand]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Withered Branch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wondrous Stone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Writ of Safid]}) /varset intKeep 0 
|-------------------------------------------------------
|Direwind Deletions:
	/if (${Cursor.Name.Equal[Ash Covered Chain Link]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ash Covered Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ash Covered Scrap Metal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ash Covered Swatch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clan Direwind Golem Stitching]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cracked Animated Bone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Direwind Voodoo Skull]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Direwrought Leather Sleeves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Golem Bone Dust]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Golem Horn]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Portal Fragment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Scratched Animated Bone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Second Fragment of the Heroes' Disk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Song: Aelfric's Last Lullaby Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Song: Wispersong of Veshma Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Absolve Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Beast's Beckoning Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Blacktalon Bite Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Blessing of Purpose Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Blistering Sunray Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Bolt of Molten Slag Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Bond of the Blacktalon Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Cloud of Wasps Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Concussive Blast Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Cure Corruption Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Diregriffon's Bite Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Draconic Rune Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Drifting Fog Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Fractured Conciousness Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Gale of the Stormborn Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Healing of Uluanes Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Magmaskin Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Mammoth's Strength Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Rune of Ellowind Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Sacred Force Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Sacred Touch Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Severan's Rot Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Shield of Darkness Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Shield of Needles Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Shield of the Crystalwing Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Sorcerous Shield Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Symbol of Elushar Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Terror of Vergalid Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Ward of the Dauntless Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tome of Blinding Flash Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tome of Phantom Silhouette Rk. II]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Twin-Edged Razorfist]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Worn Bone]}) /varset intKeep 0 
|-------------------------------------------------------
|Dragonscale Hills Deletions:
	/if (${Cursor.Name.Equal[Crank Handle with Silver Filigree]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Beetle Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Levitation Crystal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Minotaur Fur]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Minotaur Hoof]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nanzie's Handkerchief]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nanzie's Pocket Watch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shiny Beetle Claw]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Silver Clockwork Device]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Silverthread Sack]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sparkling Beetle Carapace Fragment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tough Beetle Leg]}) /varset intKeep 0 
|-------------------------------------------------------
|Droga Deletions:
	/if (${Cursor.Name.Equal[Carved Wooden Mask]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Copper Armband]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Drogan Warlord's Insignia]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Goblin Loincloth]}) /varset intKeep 0 
|-------------------------------------------------------
|Fortress Mechanotus/Steam Factory Deletions:
	/if (${Cursor.Name.Equal[Brownie Parts]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Calibration Device]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Can of Dirty Oil]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Can of Warm Oil]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Class "A" Cog]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clockwork Drive Shaft]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clockwork Gnome Gear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clockwork Gnome Shaft]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clockwork Gnome Spring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clockwork Grease]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clockwork Pinion Gear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clockwork Pinion Spring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dweric Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engineer's Toolbox]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gnome Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gnome Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grease Tin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Green Gem Grade Faycite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hex Bolt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Large Coil Spring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Large Hex Bolt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Micro-Cog]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Minotaur Blood]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Minotaur Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Oil Can]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Piece of Scrap Metal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Power Station Delta blueprints]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Purple Gem Grade Faycite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Red Gem Grade Faycite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sheet of Steel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Clockwork Screws]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Clockwork Shaft]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Coil Spring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spool of Fine Wire]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Steam Suit Hydraulic Fluid]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Steamwork Powersource]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Steel Beam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Steel Wire]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tarnished Screw]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tiny Clockwork Shaft]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Used Clockwork Spring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Yellow Gem Grade Faycite]}) /varset intKeep 0 
|-------------------------------------------------------
|Frontier Mountains Deletions:
	/if (${Cursor.Name.Equal[Brute Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Jade Magma]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Leather Whip]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Petrified Goblin Eye]}) /varset intKeep 0 
|-------------------------------------------------------
|Grimling Forest Deletions:
	/if (${Cursor.Name.Equal[Acrylia Ore Fragment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Claw of the Grunt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dirk of the Grunt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Buh]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Drum]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Drurn]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Dytl]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Gomn]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Lomn]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Moull]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Etched Acrylia Rune - Wer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flawless Aquamarine]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Golden Pendant]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Great Sword of the Grunt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grimling Finger Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grimling Toes]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hardened Driftwood Great Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hammer of the Grunt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Jade Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pearl Earring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pearl Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Howling]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shiny Ore Machete]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shiny Stone Dagger]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shiny Stone Hammer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shiny Stone Tipped Spear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Short Sword of the Grunt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sinew Wrapped Battle Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Staff of the Grunt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Treated Bone Tipped Spear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Dark Paths]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Duration]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Duress]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Endurance]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Motion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of the Suffering]}) /varset intKeep 0 
|-------------------------------------------------------
|Hills of Shade Deletions:
	/if (${Cursor.Name.Equal[Borrowed Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Borrower Egg]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ethereal Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ghostly Essence]}) /varset intKeep 0 
|-------------------------------------------------------
|Jewel of Atiiki Deletions:
	|Only fill up stacks of 20:
	/if (${Cursor.Name.Equal[Hearty Efreeti Heart]}) {
		/if (${FindItemCount[${Cursor.Name}]} != 0 && ${FindItem[${Cursor.Name}].FreeStack} == 0) {
			/varset intKeep 0
		} else {
			/varset intKeep 1
		}
	}
	
	/if (${Cursor.Name.Equal[Platinum Efreeti Boots]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Efreeti Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Efreeti Chestplate]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Efreeti Gauntlets]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Efreeti Greaves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Efreeti Helm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Efreeti Vambraces]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rough Efreeti Beard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Royal Platinum Choker]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sandy Worn Sash]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[SummonedSword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Token of Alignment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Token of Order]}) /varset intKeep 0 
|-------------------------------------------------------
|Katta Castrum Deletions:
	/if (${Cursor.Name.Equal[Fine Animating Force]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shiny Shissar Scale]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shissar Meat]}) /varset intKeep 0 
|-------------------------------------------------------
|Korafax / High SOD Deletions:
	/if (${Cursor.Name.Equal[Aligned Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bazu Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Black Arcane Power Source]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blazing-Rune Blade]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Bloodbind Potion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blood-Tempered Dagger]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bloody Note]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Boneborn Cudgel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Broken Kyv Warbow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Broken Ukun Leash]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chunk of Broken Ancient Stone Worker]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chunk of Taelosian Rock]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chunk of Taelosian Stone Worker]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dented Kyv Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Discordling Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dragorn-Rib Hook]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Empty Flask]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Essence Sieve]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Focused Thalanite Tube]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fragment of Arcanium]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[High-Octave Tuning Fork]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Kyv Heart]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mastruq's Bloodied Mane]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mastruq's Broken Facemask]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Muramite Bile Sack]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Muramite Etched Scales]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Dark Matter]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Infused Dark Matter]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sample of Taelosian Sludge]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shimmering Aligned Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sparkling Lightning Spike]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Taelosian Mountain Tea Leaves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Taelosian Mountain Wheat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Taelosian Tea Leaves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Taelosian Wheat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tendon-Hilted Scimitar]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vitrik Beak]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vitrik Claw]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vitrik Pinion Feather]}) /varset intKeep 0 
|-------------------------------------------------------
|Mines of Nurga Deletions:
	/if (${Cursor.Name.Equal[Death Mark of Nurga]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nurgan Spirit Fetish]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nurgan Taskmaster Whip]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rock Breaker Hammer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rusty Morning Star]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rusty Short Sword]}) /varset intKeep 0 
|-------------------------------------------------------
|Netherbian Deletions:
	/if (${Cursor.Name.Equal[Blood Red Stone of Loss]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Netherbian Chitin]}) /varset intKeep 0 
|-------------------------------------------------------
|Nobles Causeway Deletions:
	/if (${Cursor.Name.Equal[A Bent Half of a Dragorn Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[A Broken Dragorn Sword Tip]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[A Shattered Half of a Dragorn Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Black Bees]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bloodroot]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Damaged Feran Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Damaged Muramite Battle Blade]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Damaged Murkglider Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dark Enchanted Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Deepshadow Feran Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Discordant Crystal Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dragorn Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dragorn Greatblade]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Feran Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Feran Brain]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Feran Brainstem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Feran Heart Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Feran Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Glistening Murkglider Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Kuuan Lodestone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Murkglider Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Murkglider Brain]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Murkglider Plasma]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Murkglider Sinew]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Murkglider Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Murkglider Stomach]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ornate Dragorn Sword Hilt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Feran Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Murkglider Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rugged Murkglider Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ruined Murkglider Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shorn Murkglider Tentacle]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Trean Flies]}) /varset intKeep 0 
|-------------------------------------------------------
|Sebilis Deletions:
	/if (${Cursor.Name.Equal[Animated Shield]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Animated Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blue Slumber Fungus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Essence of Rathe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fabled Fungus Covered Scale Tunic]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flawed Defiant Amberstone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flawed Defiant Glass Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fungi Covered Great Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Green Jade Axe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 35]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 36]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 115]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 116]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 300]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 301]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nilitim's Grimoire Pg. 352]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pickled Froglok Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Robe of Living Fungus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ruby Crown]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of the Inverse]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sapphire Necklace]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Atol's Spectral Shackles]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Augment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Breath of Karana]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Call of the Hero]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Cannibalize III]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Cripple]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Circle of Winter]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Conjure Corpse]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Death Pact]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Dementia]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Dyzil`s Deafening Decoy]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Heroic Bond]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Inferno of Al'Kabor]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Omakin's Alacrity]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Pillar of Frost]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Quiver of Marr]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Reckoning]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Sedulous Subversion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Spirit of Scale]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Spirit of the Howler]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Talisman of Jasinth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Talisman of the Brute]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Tears of Druzzil]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Thrall of Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Wind of Tashani]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spores of Forgetfulness]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Star Ruby Earring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[The Scent of Marr]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wax Flower]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Burnishing]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Collection (Caza)]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Incarceration]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Obligation]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Restraint]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of the Psyche]}) /varset intKeep 0 
|-------------------------------------------------------
|SOD (Seeds of Destruction - Field of Scale (and related) Deletions:
	/if (${Cursor.Name.Equal[Backpack]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Bandages]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Bear Parts]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Belt Pouch]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Backpack]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Bixie Parts]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Bixie Stinger]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Bixie Wing]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Brick of Crude Iron Ore]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Blackrock Lichen]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Black Wolf Skin]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Black Wolf Tooth]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Blood Raven Beak]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Blood Raven Tailfeather]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Blood Raven Talon]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Burned Out Lightstone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Burnt Out Golem Animation Essence]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chokadai Carcass]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Chokadai Meat]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Cutthroat Golden Tooth]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Cutthroat Insignia Ring]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Deathfist Pawn Scalp]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Dry Eye Weed]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Empty Strong Venom Sack]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Essence of Corruption]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Fine Scorpion Meat]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Fire Beetle Eye]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Fire Beetle Leg]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Fire Beetle Patella]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Greater Lightstone]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Grifenne Blood]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Hearty Raptor Meat]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Honeycomb]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Iksar Blood]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Iksar Meat]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Iksar Ribcage]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Large Fire Beetle Patella]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Large Fire Beetle Sternite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Large Fire Beetle Tarsus]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Leaf Scarab Sternite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Leaf Scarab Tarsus]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Legionnaire's Bracer]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Lightstone]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Orc Pawn Pick]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Pristine Cladium]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Delphinium]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Pristine Larkspur]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Pristine Oleander]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Privit]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Purified Grade A Chorsine Sample]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Purified Grade A Gormar Venom]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Purified Grade A Nigriventer Venom]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Purified Grade A Taipan Venom]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Quality Caladium]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Raptor Tail Spine]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Ruined Animal Pelt]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Rusty Dagger]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Sarnak Blood]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Scarab Carapace]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Scarab Eye]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Scarab Legs]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Scorpion Carcass]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Skeleton Parts]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Small Box]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Small Cloth Gloves]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Small Cloth Wristband]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Snake Carcass]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Snake Egg]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Snake Scales]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Snake Venom Sack]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Sokokar Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sokokar Snack]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sokokar Wing Webbing]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spider Legs]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Superior Delphinium]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Superior Larkspur]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Superior Muscmol]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Superior Oleander]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Superior Privit]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Third Riddle for the Troll]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Troll Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Vial of Smoke]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Weak Choresine Sample]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Weak Gormar Venom]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Weak Larkspur Extract]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Weak Mamba Venom]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Weak Muscimol Extract]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Weak Nigriventer Venom]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Weak Oleander Extract]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Worn Great Staff]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Wrist Pouch]}) /varset intKeep 0

|-------------------------------------------------------
|Tenebrous Mountains Deletions:
	/if (${Cursor.Name.Equal[a Collector's Sonic Wolf Ear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Astral Jewel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Damaged Sonic Wolf Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Darkwing Bat Fur]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Engraved Fire Opal Sculpture]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fancy Necklace]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Frozen Vial]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Genlan's Chronicle]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Glade Dew]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Jade Earring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Jagged Reed]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lava Rock]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lunar Marked Stone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Ambidexterity]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Mountains]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Battle]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Chants]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Gallantry]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Poetry]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Swordsmanship]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of the Oracle]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Trickery]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Moon Jewel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Moonstone Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pearl Studded Medal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pouch of False Gems]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ring of Wit]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silver Amulet]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Ancient Scuplture]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Rough Marble Figurine]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sonic Wolf Ear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sonic Wolf Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sonic Wolf Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sonic Wolf Paw]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sonic Wolf Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Star Jewel]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sun Jewel]}) /varset intKeep 0 
|-------------------------------------------------------
|The Deep Deletions:
	/if (${Cursor.Name.Equal[A Lucid Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Emerald Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Memory Sphere]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mithril Amulet]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Opal Bracelet]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pain sphere]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pearl Necklace]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Song: Battlecry of the Vah Shir]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Song: Dreams of Ayonae]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Song: Elemental Chorus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Aid of Khurenz]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Beguiling Visage]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Breath of Tunare]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Decession]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Degeneration]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Disinfecting Aura]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Eagle Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Epitaph of Life]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Falcon Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Familiar]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Firetree's Familiar Augment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Foliage Shield]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Healing Wave of Prexus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Jolting Blades]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Mark of Retribution]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Mark of the Predator]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Mental Corruption]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Plague of Insects]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Regrowth of Dar Khura]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Spell Shield]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Spirit of Eagle]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Spirit of Omakin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Spirit of Snow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Succussion of Shadows]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Thunder of Karana]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Torrent of Fatigue]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Torrent of Hate]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Torrent of Pain]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Tricksters Augmentation]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Spell: Veil of Elements]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Transons Elemental Infusion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spell: Words of Tranquility]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tears of Prexus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Terror Sphere]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Thought horror fangs]}) /varset intKeep 0 
|-------------------------------------------------------
|Tirranun's Delve Deletions:
	|/if (${Cursor.Name.Equal[Air-Infused Spring Water]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Amber Water Worm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blue Nightwort]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Burnberry]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Camphor Leaf]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chipped Drake Tooth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Chunk of Ice]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crumbling Goblin Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cryptanthus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Deadly Ivy]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Deep Forest Mushroom]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Delvian Goblin Tooth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Drake-Spike]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Drake Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Drake Saliva]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Drake Wing Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Firefly]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Frothing Drake Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Jungle Pineapple]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Lime]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Luminous Ivy]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Marsh Algae]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Marsh Gas]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mature Silkworm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nest Drake Egg]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nest Drake Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nettle Creeper]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Olive]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pitcher Plant]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Red Cups]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sand-Scuffed Bone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shattered Goblin Skull]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shattered Stone Fragment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shredded Goblin Flesh]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silkworm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silkworm Larva]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simmering Basilisk Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sky Vine]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Fruit]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Starshine Moss]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Steaming Water]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Storm Cloud]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sunshard Pebble]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Tough Basilisk Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Volcanic Necklace]}) /varset intKeep 0
|-------------------------------------------------------
|The Steppes Deletions:
	/if (${Cursor.Name.Equal[CLASS 4 Steel Serrated Tip Arrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Darkfell Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Runed Oak Bow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Small Brick of Unrefined Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Steppes Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wyl`ards Cartography Tools]}) /varset intKeep 0 
|-------------------------------------------------------
|Toskirakk (and related) Deletions:
	/if (${Cursor.Name.Equal[Battle Fractured Diamond]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cask of Toskirakk Bitter]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dark Elf Parts]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Elven Blood]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Frog Eye]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Frog Mucus]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Frog Tongue]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Giant Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Goblin Parts]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Goblin Skull]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Highmaul of Anguish]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Jar of Potable Murkwater]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Ogre Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ogre Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Orc Eye]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Quality Privit]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Rallosian Iron Rations]}) /varset intKeep 0
	|TONK/if (${Cursor.Name.Equal[Shrunken Elf Head]}) /varset intKeep 0
	|TONK/if (${Cursor.Name.Equal[Signet of Guard Tregenek]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Solid Dregcheese]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Toskirakk Shackle Key]}) /varset intKeep 0
	|TONK/if (${Cursor.Name.Equal[Toskirakk Signet of the Guard]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Troll Parts]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Vial of Iksar Blood]}) /varset intKeep 0 
|-------------------------------------------------------
|Twilight Sea Deletions:
	/if (${Cursor.Name.Equal[A Faded Salil's Writ Page]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[A Faded Velishoul's Tome Page]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blackened Mace]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Charcoal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crysotherium]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Eye of Serilis]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flame of Vox]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Glove of Rallos Zek]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gloves of Rallos Zek]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gold Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ice of Velious]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Iron Oxide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Jade Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Mark of Nature]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Part of Tasarin's Grimoire Pg. 30]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Part of Tasarin's Grimoire Pg. 312]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Part of Tasarin's Grimoire Pg. 375]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Part of Tasarin's Grimoire Pg. 390]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pearl Shard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pewter Figurine]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Protector Gem]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Al'Kabor]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Arrest]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Attraction]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Banding]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Concussion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Consumption]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Contortion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Disassociation]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Dismemberment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Fulguration]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Expulsion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Karana]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Neglect]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Oppression]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Presence]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Rallos Zek]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Regeneration]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Solusek Ro]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Sorcery]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of the Catalyst]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of the Combine]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of the Cyclone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of the Helix]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Trauma]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Velious]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune of Xegony]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Russet Oxide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Salil's Writ Pg. 60]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Salil's Writ Pg. 64]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Salil's Writ Pg. 90]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Dagger]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Dirk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Great Mace]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Great Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Long Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Mace]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Scimitar]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Short Spear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Short Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Two Handed Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Warhammer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Stralagite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Stratolite]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tablet of Wolves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg. 8]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg. 9]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg.17]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg.44]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg.43]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg.67]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg.68]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg.75]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's Tome Pg.76]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Velishoul's tome Pg. 109]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Abatement]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Absorption]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Acquisition (Azia)]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Allure]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Anthology]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Bidding]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Cazic-Thule]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Cloudburst]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Coercion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Dark Paths]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Detachment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Detention]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Dimension]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Discernment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Dissemination]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Dominion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Duration]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Efficacy]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Enlightenment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Eventide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Haunting]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Mistbreath]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Motion]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Neglect]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Parasitism]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Possession]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Purification]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Quivering]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Radiance]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Recluse]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Refuge]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Resolve]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Rupturing]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Sight]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of the Extinct]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of the Incorporeal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of the Quickening]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of the Sentient (Beza)]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Words of Transcendence]}) /varset intKeep 0 
|-------------------------------------------------------
|Upper Guk Deletions:
	/if (${Cursor.Name.Equal[Exquisite Etched Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Froglok Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Froglok Eye]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Froglok Leg]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Froglok Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Froglok Poison Gland]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Golden Rod]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Green Froglok Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Lens of Glowing Amber]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shin Gauntlets]}) /varset intKeep 0 
|-------------------------------------------------------
|Valor Deletions:
	/if (${Cursor.Name.Equal[A piece of the crystalline globe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[A Planarian Larvae's Heart]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Clump of Digested Earth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ethereal Parchment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Frog Skins]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Larvae Remains]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Piece of the Crystalline Globe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Planarian Larvae's Heart]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Poison Frog Legs]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Valor Crystals]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Venomous Liquids]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Worm Guts]}) /varset intKeep 0 
|-------------------------------------------------------
|Void A Zones Deletions:
	/if (${Cursor.Name.Equal[Bat Saliva]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blackened Deathcap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Bone Chips]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fetid Flesh]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Bear Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Skeleton Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Steel Long Sword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Glob of Fine Viscous Ooze]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gold Nugget]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Handful of Grain Seeds]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Human Blood]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Human Parts]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Infected Animal Organ]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Irregular's Signet Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Low Quality Bear Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Low Quality Wolf Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Medium Quality Bear Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Medium Quality Wolf Skin]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pearlescent Snake Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Giant Bat Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Putrid Skeleton Bones]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Reanimated Bone Dust]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ruined Wolf Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rusted Blade Fragments]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Section of Fine Snake Pancreas]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Section of Rat Pancreas]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Section of Superior Rat Pancreas]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Section of Wolf Pancreas]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shimmering Snake Scales]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Snake Fang]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Snake Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Snake Venom Gland]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Versluierd Fungus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wild Bloodberry Branch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wild Blueberry Branch]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wolf Teeth]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Wolf Whiskers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Zombie Essence]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Zombie Skin]}) /varset intKeep 0 
	|Parchments:
	/if (${Cursor.Name.Equal[Contaminated Parchment Scrap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Corrupted Parchment Scrap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Defiled Parchment Scrap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Malignant Parchment Scrap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Infected Parchment Scrap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Plagued Parchment Scrap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Soiled Parchment Scrap]}) /varset intKeep 0 
|-------------------------------------------------------
|LON Playing Cards:
	/if (${Cursor.Name.Equal[Chel'Drak's Ring]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cloud of Torpor]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crushbone Officer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hollow Passageway]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Knight of E'ci]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Meatbeast]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Slashing Assault]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Slowing Poison]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Terrorantula]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Titanic Stomp]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Watery Pool]}) /varset intKeep 0 
|-------------------------------------------------------
|SOF Tradeskills:
|Fluids:
	/if (${Cursor.Name.Equal[Crude Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Excellent Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flawless Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Immaculate Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sullied Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Superb Spinneret Fluid]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Thick Spinneret Fluid]}) /varset intKeep 0 
|Gems:	
	/if (${Cursor.Name.Equal[Amber]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Bloodstone]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Jade]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Raw Amber Nihilite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Raw Crimson Nihilite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Raw Indigo Nihilite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Raw Shimmering Nihilite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Staurolite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Alexandrite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Amethyst]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Black Sapphire]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Combine Star]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Demantoid]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Goshenite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Jacinth]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Morganite]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Uncut Rubellite]}) /varset intKeep 0
|Loam:
	/if (${Cursor.Name.Equal[Alkalai Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Alkaline Loam]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Bonded Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ductile Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fused Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Malleable Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pliant Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Porous Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Salty Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Soluble Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spongy Loam]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Supple Loam]}) /varset intKeep 0 
|Marrow:
	/if (${Cursor.Name.Equal[Damp Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dry Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dusty Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Excellent Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Hemic Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Moist Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Natural Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Saturated Marrow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Superb Marrow]}) /varset intKeep 0 
|Ores:	
	/if (${Cursor.Name.Equal[Cobalt Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fulginate Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Indium Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Iridium Ore]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Rhenium Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rubicite Ore]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Sunshard Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tantalum Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Thalium Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Titanium Ore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tungsten Ore]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Vanadium Ore]}) /varset intKeep 0 
|Pelts:	
	/if (${Cursor.Name.Equal[Crude Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Excellent Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flawed Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flawless Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Immaculate Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rough Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sullied Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Superb Animal Pelt]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tattered Animal Pelt]}) /varset intKeep 0 
|Powders:	
	/if (${Cursor.Name.Equal[Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Intricate Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Modest Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Ornate Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Refined Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rune Binding Powder]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Simple Binding Powder]}) /varset intKeep 0 
|Research:
	/if (${Cursor.Name.Equal[Dirty Runic Papyrus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dirty Runic Spell Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Dirty Vellum]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grimy Fine Runic Parchment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grimy Fine Vellum Parchment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grimy Papyrus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grimy Spell Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grubby Crude Spell Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grubby Fine Papyrus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grubby Fine Parchment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Grubby Fine Vellum]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Fine Supple Runic Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Raw Supple Runic Hide]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shabby Fine Spell Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shabby Rough Spell Scroll]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shabby Runic Vellum]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Shabby Vellum Parchment]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Smudged Rough Paper]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Smudged Rough Papyrus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Smudged Runic Paper]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sooty Fine Paper]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sooty Fine Runic Papyrus]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Sooty Fine Runic Vellum]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sooty Paper]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Stained Fine Runic Paper]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Stained Fine Runic Spell Scroll]}) /varset intKeep 0 
|Runes:
	/if (${Cursor.Name.Equal[Gold Etched Eye Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Gold Etched Spiral Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Platinum Etched Eye Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silver Etched Eye Rune]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silver Etched Spiral Rune]}) /varset intKeep 0 
|Silks:
	/if (${Cursor.Name.Equal[Coarse Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Crude Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Excellent Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Exquisite Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fine Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Flawless Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Immaculate Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Natural Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Pristine Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rough Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Sullied Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Superb Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Tacky Silk]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Thick Silk]}) /varset intKeep 0 
|-------------------------------------------------------
|Other sets:
	/if (${Cursor.Name.Equal[Flawed Adept's Rake]}) /varset intKeep 0 
|Elaborate Defiant Weapons:
	/if (${Cursor.Name.Equal[Elaborate Adept's Crystal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Combatant's Crystal]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Claymore]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Cutlass]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Dayblade-]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Dragonrod]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Fireborn Axe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Flint Spear]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Greatsword]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Kama]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Minotaur Staff]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Nightblade]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Quickclaw]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Rapier]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Recurve Bow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Sceptre]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Scimitar]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Spiked Warhammer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Spikemaul]}) /varset intKeep 0 
|Elaborate Defiant Augs
	/if (${Cursor.Name.Equal[Elaborate Defiant Coldstone]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Fire Bauble]}) /varset intKeep 0 

|Elaborate Defiant Armors:
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Boots]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Coif]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Gauntlets]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Leggings]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Sleeves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Tunic]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Chain Wristguard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Leather Boots]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Leather Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Leather Cap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Leather Gloves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Leather Sleeves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Leather Trousers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Leather Tunic]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Breastplate]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Boots]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Gauntlets]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Greaves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Helm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Vambraces]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Wristband]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Plate Wristguard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Silk Cap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Silk Gloves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Silk Pantaloons]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Silk Sandals]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elaborate Defiant Silk Wristband]}) /varset intKeep 0 
|-------------------------------------------------------
|Elegant Defiant Weapons:
	/if (${Cursor.Name.Equal[Elegant Defiant Aegis]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Battleaxe]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Bow]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Fireborn Axe]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Elegant Defiant Forked Spear]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Elegant Defiant Goshenite]}) /varset intKeep 0
	|/if (${Cursor.Name.Equal[Elegant Defiant Sceptre]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Elegant Defiant Short Sword]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Elegant Defiant Shortsword]}) /varset intKeep 0
	/if (${Cursor.Name.Equal[Elegant Defiant Square Hammer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Warhammer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Knuckle Guards]}) /varset intKeep 0 
|Elegant Defiant Armors:
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Boots]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Coif]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Gauntlets]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Leggings]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Sleeves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Tunic]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Chain Wristguard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Boots]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Cap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Gloves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Sleeves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Trousers]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Tunic]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Leather Wristguard]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Elegant Defiant Breastplate]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Plate Boots]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Plate Bracer]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Plate Gauntlets]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Elegant Defiant Plate Greaves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Plate Helm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Plate Vambraces]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Plate Wristband]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Plate Wristguard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Silk Cap]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Silk Gloves]}) /varset intKeep 0 
	|/if (${Cursor.Name.Equal[Elegant Defiant Silk Pantaloons]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Silk Sandals]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Silk Sleeves]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Silk Wristband]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Silk Wristguard]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Elegant Defiant Silk Wristwrap]}) /varset intKeep 0 

|Generic Foraging Items:
	/if (${Cursor.Name.Equal[Amber Water Worms]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Blue Nightwort]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Burnberry]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Cryptanthus]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Deadly Ivy]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Draconic Essence]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Firefly]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fishing Grubs]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Fruit]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Nettle Creeper]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Rabbit Meat]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Silkworm]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Spiny Fruit]}) /varset intKeep 0 
	/if (${Cursor.Name.Equal[Roots]}) /varset intKeep 1
	/if (${Cursor.Name.Equal[Vegetables]}) /varset intKeep 0 

|-------------------------------------------------------

	
/return
